### ISSUE TITLE
versioneer does not work properly with setuptools

### ISSUE THREAD

**Issue by mithrandi** [warner/python-versioneer#101]
Versioneer's build_py class inherits from the distutils one, not the setuptools one; this seems to cause problems like wheels not being built with the right contents (I guess because distutils handles MANIFEST.in differently).

There is already code to handle this for the "sdist" command, I think doing the same for "build_py" is the correct thing to do. PR incoming.

**Comment by mithrandi** [comment]
Doh, this was already fixed in 99d5d9341830945f7080537ddd3bbd79c4aa1732. Could we get a new release that includes this fix? It seems like a major issue.

**Comment by ariscn** [comment]
With the fix you linked, I sometimes (could be Python 2.7 vs 3?) get:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/05/lzm4sx4s7nz1mrjzmvb4x5kr0000gn/T/pip-82obr2-build/setup.py", line 30, in <module>
        cmdclass=get_cmdclass(),
      File "versioneer.py", line 1459, in get_cmdclass
        if "setuptools" in sys.modules:
    AttributeError: 'NoneType' object has no attribute 'modules'
```

When running `pip install -e .` to install my package into a virtualenv for development.

**Comment by ariscn** [comment]
It looks like this relates to https://github.com/warner/python-versioneer/issues/52.

For some reason, `del sys.modules['versioneer']` seems to entirely remove `sys` when run under Python 2.7(.10). Commenting out both instances of `del` allows versioneer to work under 2.7, but re-introduces the linked issue.

**Comment by ariscn** [comment]
Okay, figured it out. I was doing:

```
from versioneer import get_cmdclass, get_version
```

I prefer this style to `import versioneer`. But because of some dark magic involving sys.modules, the former fails under 2.7 while the latter works as expected.

I'm not sure what the fix is, so I propose updating the docs to warn against the `from versioneer` syntax.

**Comment by kristi** [comment]
+1 on releasing a new versioneer version. I'm having setuptools related versioneer issues too.

**Comment by ariscn** [comment]
Found another problem! `pip install -e .` to developer a project fixes the versioneer version string at install time. I doubt that there's a way to update this dynamically, but is there at least a way to detect an editable install and construct a different version string, by adding a '-editable' suffix?

**Comment by mikebryant** [comment]
+1. Just spent several hours trying to figure out why my static data wasn't included in my wheels

**Comment by kristi** [comment]
Five months later and still no 0.16 release?

**Comment by warner** [comment]
So sorry, I've been distracted by other projects. I'll make an 0.16 release with the existing code now.

**Comment by warner** [comment]
@ariscn I think your `install -e` problem is #83 (not that there's an obvious solution, but maybe you'll find the analysis useful).

@ariscn I ran some little test programs with python 2.7.10 and 2.7.11, and didn't see `sys` getting deleted entirely. When 0.16 is out, could you re-test and open a new issue if that problem persists? I'm thinking it might involve the version of setuptools you had back in october too.

**Comment by warner** [comment]
Ok, 0.16 is out , and should include this fix. Closing this out. Sorry for the extended delay, folks.
