### ISSUE TITLE
pip install versioneer results in non functioning script on windows

### ISSUE THREAD

**Issue by fmoor** [warner/python-versioneer#104]
when I pip install versioneer on windows a `versioneer` file is created in Python27/Scripts, but it is not recognized as a python script. i.e. when I run `versioneer install` I get an error about versioneer not being a recognized command. If I change `versioneer` to `versioneer.py` and run `versioneer.py install` it works fine. 

Windows 7
python 2.7.10
pip 7.1.2

**Comment by anntzer** [comment]
Kindly bumping the issue.  Just installing the script as `versioneer.py` on Windows only should solve the issue (the user will be able to call it as `versioneer` from the command line thanks to the PATHEXT mechanism).

**Comment by James-Dengel** [comment]
I have hit this issue as well.
