### ISSUE TITLE
support for python 3.2

### ISSUE THREAD

**Issue by grzanka** [warner/python-versioneer#116]
Hi,

I would like to use python-versioneer for a Python 3.2 project. I know this Python its pretty old, but still some Linux distos has it as the newest version (i.e. Ubuntu 12.04 LTE, which has support until April 2017, Centos 6, Debian 7 etc...).
I've made an attempt to make versioneer compatible with Python 3.2, patch is minor and related to base64.b64decode method. Also travis and tox configuration has been adapted to handle an issue with python3.2 and virtualenv, see more details here: https://github.com/travis-ci/travis-ci/issues/5485
You can see PR here: https://github.com/warner/python-versioneer/pull/115
Travis tests are passing: https://travis-ci.org/grzanka/python-versioneer/builds/128785175

Cheers,
Leszek

**Comment by warner** [comment]
Landed.. thanks!
