### ISSUE TITLE
What to do with setup.py?

### ISSUE THREAD

**Issue by michaelaye** [warner/python-versioneer#118]
The documentation does not make any mention if a version string is still required in setup.py?
I noticed that `<module_name>.__version__` does not require it as things are magically done via `__input__.py` and such, but for `pip` something more seems to be required?
From the docs, I understand that `pip` has problems to find the version number from sub-directories inside the package (meaning lower than where `setup.py` is, correct?). Hence I assume that when I am in the same folder than `setup.py` things should work?
Commenting out my old hard-coded version string in `setup.py` lets `pip` assume version number "0.0.0" though:
```bash
(stable)└─❱❱❱ python setup.py sdist                                   +5660 18:58 ❰─┘
running sdist
running egg_info
writing dependency_links to pyciss.egg-info/dependency_links.txt
writing pyciss.egg-info/PKG-INFO
writing top-level names to pyciss.egg-info/top_level.txt
writing requirements to pyciss.egg-info/requires.txt
reading manifest file 'pyciss.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyciss.egg-info/SOURCES.txt'
running check
creating pyciss-0.0.0
creating pyciss-0.0.0/PYCISS.egg-info
creating pyciss-0.0.0/pyciss
...
```
Am I missing something?

**Comment by warner** [comment]
What does your setup.py look like now? The current intention is that the `version=` argument to `setup()` should use the versioneer function:

```python
setup(name="project",
      version=versioneer.get_version(),
      ...
      )
```

**Comment by michaelaye** [comment]
Sorry, I had to move on and stopped using versioneer.

**Comment by warner** [comment]
No worries.. sorry it took so long for me to get back to you. Thanks for the report and the followup!
