### ISSUE TITLE
versioneer install script does not work properly on windows

### ISSUE THREAD

**Issue by xoviat** [warner/python-versioneer#131]
The python versioneer install script does not work properly because it has no file extension. I've run into this issue in the past and there are two ways to address it:

1. Install a batch file that calls the python script and passes the command line arguments.
2. The recommended way is to use the entry_points method with the console_scripts.

It's a fairly simple fix that shouldn't take too much time to resolve, and if you want, I can put in a PR.

**Comment by xoviat** [comment]
Note: Looking at the issue about supporting Python 2.6 (???), I assume there may be some compatibility reason for not using entry_points.

**Comment by xoviat** [comment]
Duplicate #104

**Comment by warner** [comment]
Looks like a good approach.. wanna file that in a pull request?

I do want to maintain 2.6 compatibility if we can, but I don't think it means we have to avoid `entry_points=`. The only tricky part is that the script we're building is constructed from a bunch of separate pieces, so we need to intercept the process at some point to do that construction. If there's a way to switch to `entry_points=`, I'm all for it.

**Comment by xoviat** [comment]
Yeah, entry_points looks like a hornets nest due to how the project is currently organized. Best not touch it.

**Comment by azjps** [comment]
Another minor issue I came upon for using the installer with windows, I had to change the following line:
```python
with open(cfg.versionfile_source, "w") as f:
```
to 
```python
with open(os.path.normpath(cfg.versionfile_source), "w") as f:
```
everywhere (3 instances).

**Comment by xoviat** [comment]
> Yeah, entry_points looks like a hornets nest due to how the project is currently organized. Best not touch it.

That was me far overestimating the difficulty of switching to entry_points.
