### ISSUE TITLE
versioneer.py is no longer flake8-clean

### ISSUE THREAD

**Issue by warner** [warner/python-versioneer#149]
By landing #148 (to fix the README's badge rendering on github), I accidentally caused versioneer.py to stop being flake8-clean. We copy the entire README into versioneer.py, as a big docstring, and now that README has long lines (with the whole badge URL on a single line), neither README nor versioneer.py meets the flake8 requirement that all lines are less than 79 characters long.

I think the best fix at this point is to stop copying README into versioneer.py. Instead, let's just write a single paragraph or two, with a pointer to the full README on github.

**Comment by philschatz** [comment]
Oh actually, the badges could be written like this:

```
[![GH Issue Board][kanban-image]][kanban-url]
...

... (at the bottom of README.md)
[kanban-image]: https://img.shields.io/github/issues/philschatz/octokat.js.svg?label=kanban%20board%20%28gh-board%29
[kanban-url]: http://philschatz.com/gh-board/#/r/philschatz:octokat.js
```

That would likely solve the flake8 issue.

Example:
https://github.com/philschatz/octokat.js/blob/master/README.md

**Comment by warner** [comment]
Oh, cool.. I'll give that a try.
