### ISSUE TITLE
Best way to use versioneer with building Sphinx documentation

### ISSUE THREAD

**Issue by Midnighter** [warner/python-versioneer#185]
The `conf.py` file that configures the Sphinx documentation building has two entries where I would naturally like to use versioneer to insert version strings:

```python
# The full version, including alpha/beta/rc tags
release = 
# The short X.Y version assumes semantic versioning.
version = 
```

This file is typically in `docs/conf.py`. I thought I could simply use versioneer in the following way:

```python
import sys
from os.path import join, pardir, dirname

sys.path.insert(0, join(dirname(__file__), pardir))

import versioneer

release = versioneer.get_version()
```

However, versioneer fails to detect the root in this way.

```
versioneer.VersioneerBadRootError: Versioneer was unable to run the project root directory. Versioneer requires setup.py to be executed from its immediate directory (like 'python setup.py COMMAND'), or in a way that lets it use sys.argv[0] to find the root (like 'python path/to/setup.py COMMAND').
```

I have read the readme section on why detection can be hard but is there a way for me to inject the root directory since I already know it?

**Comment by Midnighter** [comment]
At that point I was actually playing with a new Sphinx extension for readthedocs that would **not** import my package. [Take a look here if you're interested in that.](https://sphinx-autoapi.readthedocs.io/en/latest/)

That didn't really work out for me, though. I guess, I'll wait until `sphinx-autoapi` becomes a bit more stable. So in the meantime I will go with your approach but I still think that a good way to get the version string by just using the versioneer module without importing your package would be really helpful.

**Comment by umangv** [comment]
OK. The other thing to try (I haven't tried it myself and I'm not associated to this project, so I really don't know) would be to use the code that versioneer inserts into `__init__.py`:

```python
from ._version import get_versions
__version__ = get_versions()['version']
del get_versions
```

So you might try

```python
sys.path.insert(0, join(dirname(__file__), pardir))
from mypackage._version import get_versions
revision = get_versions()['version']
del get_versions
```

This should work at least on code from `setup.py sdist` since that has, in `_version.py`,
```python
def get_versions():
    return json.loads(version_json)
```
