### ISSUE TITLE
versioneer doesn't work on recent pip when PEP 517 build is triggered

### ISSUE THREAD

**Issue by astrojuanlu** [warner/python-versioneer#192]
See for example:

```
 pip install git+https://github.com/satellogic/telluric.git@master
Collecting git+https://github.com/satellogic/telluric.git@master
 Cloning https://github.com/satellogic/telluric.git (to revision master) to /tmp/pip-req-build-9k8rc3xc
 Installing build dependencies ... done
 Getting requirements to build wheel ... error
 Complete output from command /home/guyd/pEnvs/test3.6/bin/python3.6 /home/guyd/pEnvs/test3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmprqjhaubw:
 Traceback (most recent call last):
   File "/home/guyd/pEnvs/test3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
     main()
   File "/home/guyd/pEnvs/test3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
     json_out['return_val'] = hook(**hook_input['kwargs'])
   File "/home/guyd/pEnvs/test3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
     return hook(config_settings)
   File "/tmp/pip-build-env-ja9d4l2j/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
     return _get_build_requires(config_settings, requirements=['wheel'])
   File "/tmp/pip-build-env-ja9d4l2j/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
     _run_setup()
   File "/tmp/pip-build-env-ja9d4l2j/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 85, in _run_setup
     exec(compile(code, __file__, 'exec'), locals())
   File "setup.py", line 2, in <module>
     import versioneer
 ModuleNotFoundError: No module named 'versioneer'
 
 ----------------------------------------
Command "/home/guyd/pEnvs/test3.6/bin/python3.6 /home/guyd/pEnvs/test3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmprqjhaubw" failed with error code 1 in /tmp/pip-req-build-9k8rc3xc
```

(by @guydou)

The root cause is this one: https://github.com/pypa/pip/issues/6163, see for example:

> I suspect the cause of this issue is that build isolation or the PEP 517 code isn't making sure that the root of the package directory is on the sys.path, because pandas has a versioneer.py sitting next to setup.py. I recall this coming up at some point, but I don't remember off the top of my head what that discussion was. This might be considered an issue with the setuptools build backend instead of pip, or it might be the fault of pip's isolation mechanism.

**Comment by daa** [comment]
It's not ``versioneer`` doesn't work but ``telluric`` does not specify ``versioneer`` in build system requirements.

**Comment by Juanlu001** [comment]
@daa adding `versioneer` to the build requirements is not listed in the installation instructions:

https://github.com/warner/python-versioneer#quick-install

If you read the linked pip comment, it explicitly says that "pandas has a versioneer.py sitting next to setup.py", so it's not a telluric problem.

**Comment by daa** [comment]
@Juanlu001 You are right, my comment wasn't thoughtful enough.

**Comment by Midnighter** [comment]
I can confirm this and additionally it was introduced with pip version 19. This works fine <19.

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /home/moritz/.virtualenvs/equilibrator/bin/python3.6 /home/moritz/.virtualenvs/equilibrator/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpseqhk02x:
  Traceback (most recent call last):
    File "/home/moritz/.virtualenvs/equilibrator/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/moritz/.virtualenvs/equilibrator/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/moritz/.virtualenvs/equilibrator/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-id6yd9kl/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-id6yd9kl/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
      _run_setup()
    File "/tmp/pip-build-env-id6yd9kl/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 30, in <module>
      import versioneer
  ModuleNotFoundError: No module named 'versioneer'

  ----------------------------------------
Command "/home/moritz/.virtualenvs/equilibrator/bin/python3.6 /home/moritz/.virtualenvs/equilibrator/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpseqhk02x" failed with error code 1 in /home/moritz/Codebase/equilibrator/equilibrator-assets
```

**Comment by yarikoptic** [comment]
so what would be the best workaround ATM?

**Comment by Midnighter** [comment]
I don't know exactly since which version of pip but versioneer works again for me (19.2.3).

**Comment by dmccreary** [comment]
I got this same error when installing the DonkeyCar 3. code on the Nvidia Nano:
ModuleNotFoundError: No module named 'versioneer'

  I had downgraded to pip 19.0 to get around the following error in pip 20.0.2:
AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'

I also tried 19.2.3 and got the same legacy error above.

Anyone have any suggestions?

**Comment by Midnighter** [comment]
Weird, I'm using pip>20 now and it works just fine with versioneer. Did you try to upgrade your setuptools version, too?

**Comment by tezelcelebi** [comment]
@dmccreary I am having the same problem. I am trying to install DonkeyCar. I downgraded to pip 19 after having **AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'**  error. 
Now I am facing the No module named 'versioneer' error.

Did you have any solution to this issue ?

**Comment by Aditya90** [comment]
I'm having a similar issue as well with the Donkey Car. Did anyone find a solution yet?

**Comment by astrojuanlu** [comment]
Could people affected by this issue try [this](https://github.com/warner/python-versioneer/issues/193#issuecomment-604025248)?

**Comment by KikeM** [comment]
Hi @astrojuanlu,

I tried that solution you suggest and it worked fine. Unfortunately, it's in one of my company's private repositories. 

Would you like the pip output in verbose mode?

**Comment by astrojuanlu** [comment]
Thanks @KikeM! No need to, `versioneer-518` works for me as well.

I was about to ask the original reporter to close this issue... but it's me :clown_face: closing!
