### ISSUE TITLE
GitHub Actions Workflow

### ISSUE THREAD

**Issue by wtgee** [warner/python-versioneer#206]
Hi, thanks for the module. I'm trying to get this working with GitHub Actions in order to publish to PyPi automatically but everything I try ends up with a `0+untagged...` version error as reported by the actions upload.  My workflow is below, but the error is:

```
Uploading panoptes_utils-0+untagged.1.ga730efa-py2.py3-none-any.whl

  0%|          | 0.00/103k [00:00<?, ?B/s]
100%|██████████| 103k/103k [00:00<00:00, 185kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: '0+untagged.1.ga730efa' is an invalid value for Version. Error: Can't use PEP 440 local versions. See https://packaging.python.org/specifications/core-metadata for url: https://test.pypi.org/legacy/
##[error]Docker run failed with exit code 1
```

Workflow is based off the old [Successful Git branching model](https://nvie.com/posts/a-successful-git-branching-model/), namely:

```bash
# Create awesome new feature
git checkout -b new-feature develop

# Go through normal PR view process and merge new feature into develop

# Create new release from develop
git checkout -b release-0.5.0 develop

# Update changelog and whatever else for release then commit
git commit -m 'Update changelog for new release'

# Tag dev release here?
git tag 0.5.0dev

# Merge into master
git checkout master
git merge --no-ff release-0.5.0

# Tag here?
git tag 0.5.0

# Push to master
git push origin master

# Push tags (but the GitHub Action has already been triggered by previous push)
git push --tags
```

There doesn't appear to be anything wrong with the GitHub Action, namely it is building and attempting to upload my package, it is just getting rejected because it thinks it doesn't have a tag.

Any tips appreciated.  Thanks!

**Comment by exarkun** [comment]
GitHub Actions doesn't fetch tags when checking out source.  You have to fix this yourself - eg by adding this after the checkout step:

```
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
```

I don't think there's anything versioneer can do about this.  If the VCS metadata has been stripped away then it's gone.  I think this was a bad choice on the part of the `actions/checkout` authors.  Maybe they'll fix it in a future version.

The only changes I can think of for Versioneer related to this are doc additions specifically about the GitHub Actions poor behavior or a more explicit failure mode in this case.  However, there is already `setup.py version` which will tell you it hasn't found any git info which points pretty directly at the problem.

**Comment by wtgee** [comment]
That seems to have done the trick. Closing for my purposes. Thanks!

**Comment by pdecat** [comment]
`actions/checkout` now allows to fetch all history for all tags and branches:

```
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
```

https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches

**Comment by moi90** [comment]
It is also important to set the `style` in setup.cfg to "pep440-pre", as per https://stackoverflow.com/a/66243061/1116842
