### ISSUE TITLE
might better to double/tripple/... license that unsafe generic "public domain"

### ISSUE THREAD

**Issue by yarikoptic** [warner/python-versioneer#36]
"is hereby released into the public domain" in itself doesn't e.g. provide any disclaimers for absent warranty etc, like any license has (e.g.BSD-3 or MIT/expat), so theoretically (IANAL) you might be left responsible for every harmful use of your code ;)   So I wondered why didn't you just release it under some very open license which would not have (virtual) any conflicts? E.g. BSD-3  or MIT/Expat... or may be both of those ;)

**Comment by itamarst** [comment]
https://creativecommons.org/publicdomain/zero/1.0/ is designed for this use case.

**Comment by FlorianWilhelm** [comment]
@yarikoptic Is public domain unsafe for users of Versioneer? I myself use a modified version of Versioneer in my PyScaffold (https://github.com/blue-yonder/pyscaffold/) package which I put under the new-BSD license. This should be fine, right?

**Comment by yarikoptic** [comment]
it might be unsafe to you (hypothetically ;) ) happen someone kills their 5billion worth of stuff somehow using versioneer... ;-)  using specific permissive license (MIT/BSD/...) is imho the best way forward with software, so yeah -- new-BSD would be good

**Comment by warner** [comment]
Thanks, CC0 sounds like exactly what I wanted.
