### ISSUE TITLE
Optionally add the branch to the package name

### ISSUE THREAD

**Issue by FlorianWilhelm** [warner/python-versioneer#49]
Assume that for your library `my_lib` you have a `master` and a `develop` branch and you let a continuous integration system like Jenkins build releases for each commit on these branches so that bleeding-edge developers can easily install current development builds of your library. Now just by looking at the `pip freeze` output it is next to impossible to see if you have installed `my_lib` from the current development branch or master branch. It would be useful if there was an option in versioneer so that in case of a non-master branch like develop the branch is suffixed to the package like `my_lib_develop-1.1-121-gebab194`. I know that the ambiguity could also be resolved by building only tagged releases on the master branch but I think my suggestion would make it more explicit.

**Comment by warner** [comment]
I like it! I think, with the new template stuff we're working on, that this will be possible, at least if you're building from a git checkout. (tarballs created with git-archive might work too). I'll look into it.

**Comment by warner** [comment]
The template stuff didn't end up quite the way I was expecting, so this isn't currently as easy as adding a `%(branch)s` to a config string somewhere. But in the current code, I think we can at least add a `["branch"]` key to the `get_versions()` dictionary, which would be available when you build from a git checkout. It might be possible to make this available from a git-archive tarball too, and from an sdist created from one of those two cases.

**Comment by FlorianWilhelm** [comment]
I am not using Versioneer any longer and `setuptools_scm` which is included in `PyScaffold` works actually better for me. Thus, I'll close this.
