### ISSUE TITLE
_version.py should conform to PEP8

### ISSUE THREAD

**Issue by roskakori** [warner/python-versioneer#56]
Currently versioneer creates a `_version.py` with a few minor PEP8 violations. This is slightly annoying for projects where the build process includes a PEP8 validation. It can easily be fixed using

    $ autopep8 -i _version.py

Nevertheless it could be nice if versioneer builds a clean `_version.py` out of the box.

**Comment by warner** [comment]
Thanks for the fix. I added a .travis.yml change to run `flake8` over the generated `_version.py` so we'll catch any future problems. I wouldn't mind making `versioneer.py` itself PEP8-compatible.. have you run into problems because of complaints therein? Or do you avoid that by not running e.g. flake8 on the top-level files like `setup.py` and `versioneer.py`?

I started to fix `versioneer.py` (which really means fixing the various source files that are used to generate it), and immediately got stuck with the travis "Build Status" image link in the README.md (which gets copied into the `versioneer.py` docstring), as the line is too long. I don't know how to split it without breaking the link. Any ideas?

**Comment by roskakori** [comment]
Thanks for improving PEP8 compatibilty and considering to further improve it.

Your assumption is correct, I'm currently excluding `versioneer.py` from the flake8 check in my project, so it's not a big deal right now.

I'm not sure if I understand the issue with you image link correctly. AFAIK flake8 does not check the README.md so I assume you are referring to Python code generating a REAME.md?

First, you can set the maximum line length for flake8 using a command line option or ini file. I never saw a point to limit my code to 79 chars on a 25 inch monitor, so I use:

```ini
[flake8]
exclude = cutplace/_version.py
ignore = E127,E128,E501
max-line-length = 159
```
Also there are several ways to split a long string across multiple lines in Python, e.g.
```python
x = 'a string ' \
   + 'spawning multiple ' \
   + 'lines.

x = ''.join([
    'a string',
    ' spawning multiple ',
    'lines'
])

# Correct but confusing to many people.
x = 'a string ' \
    'spawning multiple ' \
    'lines'
```
Does this help in solving you issue?

**Comment by warner** [comment]
> I'm not sure if I understand the issue with you image link correctly. AFAIK flake8 does not check the README.md so I assume you are referring to Python code generating a REAME.md?

It's the other way around: `versioneer.py` is constructed by combining several source files, most of which are python, but it also embeds the README.md as a large triple-quoted docstring (look at the beginning of version.py).

The README.md includes a link to a Travis-CI build-status image. The line that contains that link is really long. Therefore `versioneer.py` winds up with a really long line in its docstring. That long line is what flake8 is complaining about.

I'd feel bad about asking downstream folks to modify their flake8 config just to deal with `versioneer.py`, so I'd like everything generated by Versioneer, including `versioneer.py`, including that docstring, to satisfy an unmodified/unconfigured flake8 run.

For python code, we can break up long lines with some minor rewriting. But this one particular line needs to remain valid Markdown so it continues to work in the original README.md, and I don't know Markdown well enough to see how to write shorter links when the URLs are long.

I suppose I could change the tool that builds `versioneer.py` to strip out that link.. that might end up being the easiest solution.

**Comment by roskakori** [comment]
Ok, now I understand.

Which part if the code converts the README.md to Python source? Are you referring to `get(fn=...)` in `setup.py`? Specifically these lines:
```python
if do_readme:
        text = text.replace("@README@", get("README.md"))
```

**Comment by roskakori** [comment]
Here's a function that should be a good base for an improved `setup.get()` which should work both under Python 2.6 and Python 3 (also see my notes on unicode strings in #62):

```python
from __future__ import unicode_literals

import io

def text_from_file_as_python_literal(path, max_length=78, quote="'"):
    with io.open(path, 'r', encoding='utf-8') as text_file:
        text = text_file.read()
    # TODO: Process various things in text, e.g. @README@ etc.
    quotes = quote * 3
    assert quotes not in text
    result = quotes + '\n'
    line_length = 0
    c = None  # Only necessary in case text is empty.
    for c in text:
        if c == '\n':
            line_length = 0
        else:
            if line_length == max_length:
                # Break too long line.
                result += quotes + '\n' + quotes
                line_length = len(quotes)
        line_length += 1
        result += c
    if c != '\n':
        result += '\n'
    result += quotes
    return result
```
Example usage:
```python
print(text_from_file_as_python_literal('README.md', 78))
```

**Comment by caktux** [comment]
one left: `_version.py:117:63: E226 missing whitespace around arithmetic operator`
