### ISSUE TITLE
dirty versions are not PEP440 compatible

### ISSUE THREAD

**Issue by marscher** [warner/python-versioneer#60]
Is it possible to achieve compatibility?

newest setuptools raises a warning:

setuptools-11.3.1-py2.7.egg/setuptools/dist.py:292: UserWarning: The version specified ('1.0a1-83-g89149e7') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

**Comment by warner** [comment]
should be fixed in PR #67 . That version should now look like "1.0a1+83.g89149e7" . If the source tree were dirty, it would look like "1.0a1+83.g89149e7.dirty". Both should be accepted by setuptools.
