### ISSUE TITLE
pep440 style and tagged version question

### ISSUE THREAD

**Issue by ldath** [warner/python-versioneer#85]
Is this normal that for exact tagged version when distance == 0 I have `TAG+DISTANCE.gHEX.dirty` version and not just `TAG` version ?

Without change form `if pieces["distance"] or pieces["dirty"]:` to `if pieces["distance"]:` I do not know how to create stable final packages.

**Comment by warner** [comment]
If you have distance==0 and dirty==False, then you should get just `TAG`: that's how to create stable final packages.

If you have distance==0 and dirty==True, then yeah, you should at least get the `.dirty` suffix. Final packages should be built from tagged and *non-dirty* trees. Does your build process modify source code just before making a release? Is there a way to change your build process to not do that?

I guess we don't strictly need to add `+DISTANGE.gHEX` too.. the `.dirty` marker is probably sufficient warning that a bug report is running from modified source (and therefore you, as the maintainer/triager, have no idea what exact they were running). But it does make it more clear that something unusual is going on.

What build process are you using? The standard `setup.py install` / `setup.py sdist` processes are supposed to modify the `_version.py` in the `build/` directory, not the source directory, so they shouldn't cause a "dirty" tree. There was an older version that didn't do this correctly (in particular when doing e.g. `setup.py sdist register upload`), but I thought we'd fixed that.

If you do a "final build", and then do a "git status", what does it report as being modified?

**Comment by ldath** [comment]
My problem is connected with this part:

```python
def git_pieces_from_vcs(tag_prefix, root, verbose, run_command=run_command):
    ...
    describe_out = run_command(GITS, ["describe", "--tags", "--dirty",
                                      "--always", "--long"],
                               cwd=root)
    ...
```
This generate command:
```bash
git describe --tags --dirty --always --long
```
In result I have: `1.0.0.1-0-g08ac2f2` 
To give more data:
```
*   08ac2f2 - (19 hours ago) Merged in ..../..... (pull request #371) (HEAD, tag: 1.0.0.1, origin/master, origin/HEAD
```
This is a fresh clone made by me for this test:
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

**Comment by warner** [comment]
Yeah, the `--long` is what forces `git describe` to give us a suffix of `-0-gHEX`, even when we're sitting on a tag. The rest of the code in `git_pieces_from_vcs()` splits out the separate fields, and then the rendering code (function `render_pep440()` in `src/render.py`) makes the decision to include or not include the suffix according to distance/dirty as you noted. The pep440 renderer will only include the suffix if the distance is nonzero or if the tree is dirty.

So even though that internal `git describe` command is reporting `1.0.0.1-0-g08ac2f2`, Versioneer itself (e.g. `setup.py --version`) should be telling you `1.0.0.1`.

Is it telling you something different?

**Comment by ldath** [comment]
You have right. I do not know why I had dirty sufix in the end before. Probably my project structure where:
```
versionfile_source = myproject/_version.py
versionfile_build = myproject/_version.py
```
is a reason.

Just close a issue. When I have more time I'll check more. In this moment I'm using modified version of versioneer in this project to solve this case in it.

**Comment by warner** [comment]
Ok, great. Feel free to file a new issue if the problem shows up again.
