### ISSUE TITLE
Wrong versioneer.py location warning on Windows

### ISSUE THREAD

**Issue by MrLeeh** [warner/python-versioneer#93]
If i run versioneer on Windows I always get the following warning:

`Warning: build in C:\Users\Lehmann\data\python\python34\moistcalc is using versioneer.py from c:\Users\Lehmann\data\python\python34\moistcalc\versioneer.py`

Actually both pathes are the same, just the drive letters are one time in upper case, second in lower case. Under Windows both represent the same directory.

So I suggest to use `os.path.normcase` for path comparison which normalizes pathes on Windows and leaves Unix/Linux pathes untouched.

**Comment by warner** [comment]
Does the fix in that 93-winpath branch fix this? (run `setup.py make_versioneer` in a patched source tree to make a new `versioneer.py`, or `setup.py build` to make a new `versioneer` installer).

**Comment by smessmer** [comment]
Same problem in Mac OS X. It seems to be related to the case sensitivity of the path.

**Comment by warner** [comment]
I haven't gotten any feedback as to whether the branch fixes this or not, but it's a pretty safe change, so I'm going to land it anyways. It'll be in the next release.
