### ISSUE TITLE
Source download version doesn't work if your clone doesn't have tags

### ISSUE THREAD

**Issue by pelson** [warner/python-versioneer#99]
It is a bit obvious, now I think about it, but exported zip files don't have a useful version if they come from a repo which doesn't have any tags, such as a fork of another.

Any thoughts on what we could change to versioneer to make this do something useful?

**Comment by warner** [comment]
Exported as in "git archive"? Yeah, we don't get much information there: the expanded keywords only contain the full SHA1 revision, and any tags used as the "tree-ish" argument to git-archive. Clones of a repo could still get tags from the parent (maybe it depends on how you do the clone), but if they aren't there, then the full revision is all we've got to work with.

What does your build process look like? Is it possible to fetch tags into your clone before running git-archive? As a last-ditch effort, remember that Versioneer looks at the parent directory name for a version string. So maybe some outer tree can somehow compute the proper (tagged) version, pass it in, then the inner tree can use it as the --prefix= argument to git-archive, to put the .zip contents in a subdirectory that includes the version string. At the end of the day, when versioneer inside the unpacked .zip file looks around, it can use the directory name.
